name: instana_agent
description: An Instana agent to collect statistics about sessions and HTTP requests for Flutter-based apps.
version: 3.0.9
homepage: https://www.instana.com
repository: https://github.com/instana/flutter-agent

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^6.2.0
  js: ^0.6.3

dev_dependencies:
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.instana.flutter.agent
        pluginClass: InstanaAgentPlugin
      ios:
        pluginClass: InstanaAgentPlugin
      web:
        pluginClass: InstanaAgentPlugin
        fileName: instana_agent_web.dart
